# Generated by Django 4.2.5 on 2023-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traval_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
